### ISSUE TITLE
Update README with v8 changes

### ISSUE THREAD

**Issue by wegry** [SentiaAnalytics/bs-css#104]
Changes:

- [ ] Emotion is now the backing library. If you're using tools like browserslist, you should see less unnecessary autoprefixing. #94 
- [ ] `merge` no longer merges a `list(list(rule))` and instead only merges `list(string)` into a string. If you need the old list behavior, `List.concat` has you covered. #97 
- [ ] Rule lists are applied in the order they are provided instead of reversed like they were in v7. #96 
- [ ] Font weight now requires the use of the num polymorphic variant instead of just ints. #98

**Comment by giraud** [comment]
Hi, checkout the v8 branch, this is where the readme and other are updated. it doesn't impact current github landing page until it is released

**Comment by wegry** [comment]
@giraud do you think the changelist above would be something we could put in the v8 readme? Or maybe it should just go in release notes?

**Comment by giraud** [comment]
@wegry did you looked at the CHANGELOG.md in v8 ? they should go there

**Comment by wegry** [comment]
I did not. Thanks for pointing it out. :wink:
